version: '3'
services:
  picam:
    build:
      context: './picam/'
      dockerfile: Dockerfile
      args:
        - userid=${DCUSERID}
        - groupid=${DCGRPID}
        - vidid=${VIDID}
        - i2cid=${I2CID}
        - spiid=${SPIID}
        - gpioid=${GPIOID}
    image: 'picam'
    ports:
      # This one is only needed if using the streamer which
      #   uses the basic python http server
      - 8675:8675
    container_name: 'picam'
    user: ${DCUSERID}
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/vcsm:/dev/vcsm
    volumes:
      - /opt/vc/lib:/opt/vc/lib
      - ${DCDATADIR}/snapper:/home/lig/snaps
      - ${DCDATADIR}/logs/snapper/:/home/lig/logs/
    restart: always
    networks:
      - default

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ${DCDEVDIR}/picam/www:/home/lig/www
      - ${DCDATADIR}/snapper:/home/lig/www/snapshots
#      - ${DCDATADIR}/logs/snapper:/home/lig/snaps/logs/
      - ${DCDEVDIR}/config/nginx.conf:/etc/nginx/nginx.conf
      - ${DCDEVDIR}/config/nginx-app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - picam
    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge
